package br.com.nexus.tops.main;

public enum RankingType {

    SIMPLE_CLANS_KDR(),
    SIMPLE_CLANS_KILL(),
    SIMPLE_CLANS_DEATH(),
    SIMPLE_CLANS_MEMBER_KDR(),
    SIMPLE_CLANS_MEMBER_KILL(),
    SIMPLE_CLANS_MEMBER_DEATH(),
    MONEY(),
    MAMBA_FACTIONS_MEMBER_DEATH(),
    MAMBA_FACTIONS_MEMBER_KILL(),
    MAMBA_FACTIONS_MEMBER_KDR(),
    MAMBA_FACTIONS_DEATH(),
    MAMBA_FACTIONS_KILL(),
    MAMBA_FACTIONS_KDR();

}
